
#git.systementor.se/yacloud/yagolangsite

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yagolangsite
  namespace: yatest
  labels:
    app: yagolangsite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yagolangsite
  template:
    metadata:
      labels:
        app: yagolangsite
    spec:
      containers:
        - name: yagolangsite
          image: git.systementor.se/yacloud/yagolangsite
          ports:
            - containerPort: 8080
          env:
            - name: RUNENVIRONMENT
              value: Production
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  namespace: yatest
  name: yagolangsite-service
  labels:
    app: yagolangsite
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  livenessProbe:
    httpGet:
        path: /healthz    
  readinessProbe: 
    httpGet:
        path: /healthz    
  selector:
    app: yagolangsite
  sessionAffinity: None